/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeDemo */

#ifndef _Included_NativeDemo
#define _Included_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeDemo
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeDemo_init
  (JNIEnv *, jobject);

/*
 * Class:     NativeDemo
 * Method:    deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeDemo_deinit
  (JNIEnv *, jobject);

/*
 * Class:     NativeDemo
 * Method:    hello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_NativeDemo_hello
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
