/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_voice_recognizer_vad_VadApi */

#ifndef _Included_com_voice_recognizer_vad_VadApi
#define _Included_com_voice_recognizer_vad_VadApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_voice_recognizer_vad_VadApi
 * Method:    create
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_voice_recognizer_vad_VadApi_create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_voice_recognizer_vad_VadApi
 * Method:    delete
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_voice_recognizer_vad_VadApi_delete
  (JNIEnv *, jobject);

/*
 * Class:     com_voice_recognizer_vad_VadApi
 * Method:    start
 * Signature: (Lcom/voice/recognizer/VadApi/VadApiCallback;)I
 */
JNIEXPORT jint JNICALL Java_com_voice_recognizer_vad_VadApi_start
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_voice_recognizer_vad_VadApi
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_voice_recognizer_vad_VadApi_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_voice_recognizer_vad_VadApi
 * Method:    reset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_voice_recognizer_vad_VadApi_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_voice_recognizer_vad_VadApi
 * Method:    feed
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_voice_recognizer_vad_VadApi_feed
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_voice_recognizer_vad_VadApi
 * Method:    setting
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_voice_recognizer_vad_VadApi_setting
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
